[package]
name = "dimensify"
version = "0.1.0"
edition = "2021"

[lints]
rust.unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(feature, values("dim2", "f64"))',
] }

[features]
default = ["wasm-bindgen"]
parallel = ["rapier3d/parallel", "num_cpus"]
wasm-bindgen = ["instant/wasm-bindgen"]

[package.metadata.docs.rs]
features = ["parallel"]

[dependencies]
nalgebra = { version = "0.33", features = ["rand", "glam027"] }
rand = "0.8"
rand_pcg = "0.3"
instant = { version = "0.1", features = ["web-sys", "now"] }
bitflags = "2"
num_cpus = { version = "1", optional = true }
crossbeam = "0.8"
bincode = "1"
md5 = "0.7"
serde = { version = "1", features = ["derive"] }

# bevy_egui = "0.29"
bevy_egui = {version="0.29.0", features = [
    # "manage_clipboard",
    "open_url", "default_fonts", "render"],default-features = false }

bevy_ecs = "0.14"
bevy_core_pipeline = "0.14"
bevy_pbr = "0.14"
#bevy_prototype_debug_lines = { version = "0.7", features = [ "3d" ] }
bevy = "0.14.2"
bevy_editor_pls = "0.10.0"
# bevy_editor_pls = {path = "../bevy_editor_pls/crates/bevy_editor_pls/", version = "*"}
# bevy_editor_pls = "0.9.0"
Inflector = "0.11.4"

#bevy_webgl2 = "0.5"
bevy-trait-query = "0.5.1"
derive_builder = "0.20.1"
thiserror = "1.0.64"
paste = "1.0.15"
derive_more = { version = "1.0.0", features = ["display"] }
fomat-macros = "0.3.2"
bevy-inspector-egui = {features = ["highlight_changes"], version = "0.26.0"}

[dependencies.rapier3d]
package = "rapier3d"
version = "0.22.0"
features = ["serde-serialize", "debug-render", "profiler"]

[patch.crates-io]
# update when this gets merged. https://github.com/JoJoJet/bevy-trait-query/issues/59
bevy-trait-query = { git = "https://github.com/RobWalt/bevy-trait-query.git", branch = "bevy-0.14-partial-update" }
bevy_editor_pls = { git = "https://github.com/soraxas/bevy_editor_pls", branch = "feat-bump-version" }

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
